@endpoint = http://localhost:3000/api/v1/cars
@authEndpoint = http://localhost:3000/api/v1/auth
@adminEmail = joe99@gmail.com
@adminPassword = password

### 0) Login as admin and capture token
# @name loginAdmin
POST {{authEndpoint}} HTTP/1.1
Content-Type: application/json

{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}
###

@accessToken = {{loginAdmin.response.body.$.accessToken}}

### 1) POST (valid) - create a car
# @name postCarSuccess
POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "make": "Kia",
    "model": "Rio",
    "color": "black",
    "yearOfCar": "2005-03-15"
}
###

@carId = {{postCarSuccess.response.body.$._id}}


### 2) POST (invalid)
# @name postCarInvalid
POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "make": "",
    "model": "Civic",
    "color": "Invisible",
    "yearOfCar": "not-a-date"
}

### 3) GET collection
# @name getCars
GET http://localhost:3000/api/v1/cars HTTP/1.1

### 4) GET individual (success)
# @name getCarSuccess

GET {{endpoint}}/691464bdc78af721812036ce HTTP/1.1

### 5) GET individual (not found)
# @name getCarNotFound
GET {{endpoint}}/000000000000000000000000 HTTP/1.1

### 6) PUT (success)
# @name putCarSuccess
PUT {{endpoint}}/{{carId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "make": "Kia",
    "model": "Rio",
    "color": "Blue",
    "yearOfCar": "2006-06-20"
}

### 7) PUT (not found)
# @name putCarNotFound
PUT {{endpoint}}/000000000000000000000001 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "make": "Ford",
    "model": "Focus",
    "color": "Green",
    "yearOfCar": "2010-01-01"
}

### 8) PUT (invalid)
# @name putCarInvalid
PUT {{endpoint}}/{{carId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "make": "",
    "model": "",
    "color": "NotAColor",
    "yearOfCar": "abcd"
}

### 9) DELETE (success)
# @name deleteCarSuccess
DELETE {{endpoint}}/690c8d8b0827f85ebe00e438 HTTP/1.1
Authorization: Bearer {{accessToken}}

### 10) DELETE (not found)
# @name deleteCarFail
DELETE {{endpoint}}/690c8d8b0827f85ebe00e438 HTTP/1.1
Authorization: Bearer {{accessToken}}

###
DELETE {{endpoint}} HTTP/1.1
Authorization: Bearer {{accessToken}}
