@endpoint = http://localhost:3000/api/v1/users
@authEndpoint = http://localhost:3000/api/v1/auth
@adminEmail = joe99@gmail.com
@adminPassword = password

### Login as admin and capture token
# @name loginAdmin
POST {{authEndpoint}} HTTP/3.0
content-type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

###
@accessToken = {{loginAdmin.response.body.$.accessToken}}

### 
### POST Request for a contact  
## Expected result is ........ 

POST {{endpoint}} HTTP/3.0 
content-type: application/json 
Authorization: Bearer {{accessToken}}

{
    "name": "Dara O'Rourke",
    "email": "S00252121@atu.ie",
    "phonenumber": "0876543210",
    "dob": "2002-05-15"
}

###

# @name postAUser



POST {{endpoint}} HTTP/3.0 
content-type: application/json 
Authorization: Bearer {{accessToken}}

{
    "name": "Monday is here",
    "email": "jdoe333@gmail.com",
    "phonenumber": "0871234567",
    "dob": "2000-01-01"
}   

###

@newObjectID = {{postAUser.response.headers.location}}

###
GET {{endpoint}}/{{newObjectID}}

### 
